services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: docker_tut
      MYSQL_ROOT_PASSWORD: password123@
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/docker_tut
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123@

volumes:
  mysql_data:
